# tenderly:
#   access_key: ""
#   account_id: ""
#   project_slug: ""

addresses:
  inst: "0x6f40d4A6237C257fff2dB00FA0510DeEECd303eb"
  governor: "0x0204Cd037B2ec03605CFdFe482D8e257C765fA1B"
  proposer: "0xA45f7bD6A5Ff45D31aaCE6bCD3d426D9328cea01"
  delegator: "0x5AAB0630aaCa6d0bf1c310aF6C2BB3826A951cFb"
  castVotes:
    - "0xC7810aA3b0c6A2778EEcC114B93d59B2E9Da9E05"
    - "0xa7615cd307f323172331865181dc8b80a2834324"
    - "0xA45f7bD6A5Ff45D31aaCE6bCD3d426D9328cea01"
governance:
  voting_delay: 13140
  voting_period: 13140
  timelock_delay: 86400
fluid:
  staging_url: "https://staging.fluid.io"
  production_url: "https://fluid.io"
github:
  # GitHub integration settings (optional, used for local dev)
  # token: ""  # Set via GITHUB_TOKEN environment variable
  # repo: ""   # Set via GITHUB_REPOSITORY environment variable
  # pr_number: # Set via PR_NUMBER environment variable
